# Generated by Django 4.0.4 on 2022-04-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Дата написания'),
        ),
    ]
