# Generated by Django 4.0.4 on 2022-04-30 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_author', to='books.author', verbose_name='авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='book_genre', to='books.genre', verbose_name='жанры'),
        ),
    ]
